server:
  port: 0
spring:
  application:
    name: user
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR}
        file-extension: yaml
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
  config:
    import:
      - nacos:user
      - optional:nacos:cache
      - optional:nacos:redis
      - optional:nacos:knife4j
      - optional:nacos:druid
      - optional:nacos:sa-token
      - optional:nacos:mybatis-plus
      # - optional:nacos:seata



