server:
  port: 0
spring:
  application:
    name: user
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR}
        file-extension: yaml
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
  config:
    import:
      - nacos:user
      - optional:nacos:cache
      - optional:nacos:redis
      - optional:nacos:mybatis
      - optional:nacos:knife4j
      - optional:nacos:druid
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 是否在控制台打印 sa-token 的 logo
  is-print: false

# seata:
#   tx-service-group: ${spring.application.name}-group
#   application-id: ${spring.application.name}
#   service:
#     vgroup-mapping:
#       user-group: default
#     grouplist:
#       default: 127.0.0.1:8091 # seata-server address