server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR}
        file-extension: yaml
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
  config:
    import:
      - nacos:gateway
# logging:
#   config: classpath:log4j2.xml